# Generated by Django 2.0.7 on 2018-08-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20180822_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='obtained_marks',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='scorepoints',
            name='mark_obtained',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
