# Generated by Django 2.0.7 on 2018-09-18 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20180822_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('quiz.subject',),
        ),
        migrations.AlterField(
            model_name='module',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='quiz.Subject'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.PositiveSmallIntegerField(help_text='*duration is in minutes'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'S'}, on_delete='models.CASCADE', related_name='score_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
